version: '3'

services:
  game_app:
    build:
      context: ./Game
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  fastapi_app:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - game_app

  nginx_proxy:
    image: nginx
    restart: always
    volumes:
      - ./Server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
    command: nginx -g "daemon off;"
