version: '3'

services:
  game_app:
    build:
      context: ./Game
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"  
    networks:
      - Ruleta

  fastapi_app:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    volumes:      
      - /etc/CertsFunCombat/privatekey.pem:/etc/CertsFunCombat/privatekey.pem
      - /etc/CertsFunCombat/cert.pem:/etc/CertsFunCombat/cert.pem
    ports:
      - "8000:8000"
    depends_on:
      - game_app
    networks:
      - Ruleta

  nginx_proxy:
    image: nginx
    restart: always
    volumes:
      - ./Server/nginx.conf:/etc/nginx/nginx.conf
      - /etc/CertsFunCombat/privatekey.pem:/etc/CertsFunCombat/privatekey.pem
      - /etc/CertsFunCombat/cert.pem:/etc/CertsFunCombat/cert.pem
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - fastapi_app
    command: nginx -g "daemon off;"
    networks:
      - Ruleta

networks:
  Ruleta:
    driver: bridge
