import { Archivo } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import paleta from "../styles/paletaColores";
import { Sidebar } from "@/Components/Sidebar/Sidebar";
const inter = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} row gap 2`}
        style={{ background: paleta.NEGRO, color: paleta.BLANCO }}
      >
        <div className="col-2">
          <Sidebar/>
        </div>
        <div className="col-12  col-lg-10 ">{children}</div>
      </body>
    </html>
  );
}
