import { Archivo } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import paleta from "../styles/paletaColores";
import { Menu } from "@/Components/Menu/Menu";
import SalasCard from "@/Components/Salas";
const inter = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} row`}
        style={{ background: paleta.NEGRO, color: paleta.BLANCO }}
      >
        <div className="col-2">
          <Menu />
        </div>
        <div className="col-12  col-lg-10 me-sm-0 semMarginRow">
          <SalasCard />
          {children}
        </div>
      </body>
    </html>
  );
}
