"""nuevas colunas tabela saque

Revision ID: 27f998c08ee9
Revises: 97a0f45493c1
Create Date: 2023-12-12 15:11:56.081001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f998c08ee9'
down_revision: Union[str, None] = '97a0f45493c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaccionesSalida', sa.Column('llavePix', sa.String(), nullable=True))
    op.add_column('transaccionesSalida', sa.Column('tipoLlave', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaccionesSalida', 'tipoLlave')
    op.drop_column('transaccionesSalida', 'llavePix')
    # ### end Alembic commands ###
