"""Inidice lado Ganador

Revision ID: 3d6cbe854bfe
Revises: a8112c47255d
Create Date: 2023-12-04 14:13:37.261354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6cbe854bfe'
down_revision: Union[str, None] = 'a8112c47255d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadas', sa.Column('IndiceGanador', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadas', 'IndiceGanador')
    # ### end Alembic commands ###
