"""Nova coluna data Criacion del usuario

Revision ID: 6debbf794d16
Revises: e5035ed6a0fb
Create Date: 2023-11-23 15:48:29.120686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6debbf794d16'
down_revision: Union[str, None] = 'e5035ed6a0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dataCriacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dataCriacion')
    # ### end Alembic commands ###
