"""campo ruleta en el modelo de la jugada

Revision ID: 9011d1cf68a4
Revises: a3a4d3186ff7
Create Date: 2023-11-25 22:39:38.499010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9011d1cf68a4'
down_revision: Union[str, None] = 'a3a4d3186ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadas', sa.Column('ruleta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadas', 'ruleta')
    # ### end Alembic commands ###
