"""ApuestaModel_gastoAccount_gastoGanancia

Revision ID: 97a0f45493c1
Revises: d93a67cd6050
Create Date: 2023-12-10 11:34:37.793278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a0f45493c1'
down_revision: Union[str, None] = 'd93a67cd6050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apuestas', sa.Column('gastoAccount', sa.Float(), nullable=True))
    op.add_column('apuestas', sa.Column('gastoGanancia', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apuestas', 'gastoGanancia')
    op.drop_column('apuestas', 'gastoAccount')
    # ### end Alembic commands ###
