"""Novas Conlunas usuario

Revision ID: a3a4d3186ff7
Revises: 69a3cc6cb504
Create Date: 2023-11-23 22:12:49.758513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a4d3186ff7'
down_revision: Union[str, None] = '69a3cc6cb504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codIndicacion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codIndicacion')
    # ### end Alembic commands ###
