"""actualizacion de relaciones entre tablas

Revision ID: d8089d4e5d4d
Revises: 507d44237fa5
Create Date: 2023-11-15 22:09:03.163352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8089d4e5d4d'
down_revision: Union[str, None] = '507d44237fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
