"""usuarioAdministrador

Revision ID: d93a67cd6050
Revises: 3d6cbe854bfe
Create Date: 2023-12-06 12:36:26.528978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93a67cd6050'
down_revision: Union[str, None] = '3d6cbe854bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usuarioAdministrador', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usuarioAdministrador')
    # ### end Alembic commands ###
