"""agregando campo ganancias

Revision ID: e5035ed6a0fb
Revises: b9f5376704f3
Create Date: 2023-11-19 20:32:48.571785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5035ed6a0fb'
down_revision: Union[str, None] = 'b9f5376704f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ganancias', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ganancias')
    # ### end Alembic commands ###
